import Header from '@/components/Header'
import { Metadata } from 'next'
import { Fira_Sans } from 'next/font/google'
import '@/styles/globals.css'

const firaSans = Fira_Sans({ subsets: ['cyrillic'], weight: '400' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={firaSans.className}>
				<Header />
				{children}
			</body>
		</html>
	)
}
